name: flutter_awesome_logger_dio
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_awesome_logger:
    path: ../flutter_awesome_logger


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


