name: flutter_awesome_logger
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  #device_info_plus: ^9.0.2
  package_info_plus: ^8.0.2
  http: ^1.2.2
  sensors_plus: ^6.0.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.20.3
  build_runner: ^2.4.13

