name: flutter_awesome_logger
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # upgrade drift version
  drift: ^2.19.1+1
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  drift_flutter: ^0.1.0
  http: ^1.2.2
  dio: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.19.1
  build_runner: ^2.4.12

flutter:
